=== pycckuu225/kt2XML/schemaFile.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="123"
  xmlns="123"
  elementFormDefault="qualified">


<xs:complexType name="OfficeType">
    <xs:simpleContent>
        <xs:extension base="xs:string">
            <xs:attribute name="code" type="xs:ID" use="required"/>
        </xs:extension>
    </xs:simpleContent>
</xs:complexType>

<xs:complexType name="NameType">
    <xs:sequence>
        <xs:element name="first" type="xs:string"/>
        <xs:element name="surname" type="xs:string"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="AdressType">
    <xs:all>
        <xs:element name="street" type="xs:string"/>
        <xs:element name="city" type="xs:string"/>
        <xs:element name="index" type="sixDigits"/>
    </xs:all>
</xs:complexType>

<xs:complexType name="phoneType">
    <xs:sequence>
        <xs:element name="phone" type="phoneStructureType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="PhoneAttributeType">
    <xs:simpleContent>
        <xs:extension base="xs:string">
            <xs:attribute name="type" type="forPhone" use="optional"/>
        </xs:extension>
    </xs:simpleContent>
</xs:complexType>

<xs:simpleType name="forPhone">
    <xs:restriction base="xs:string">
        <xs:enumeration value="work"/>
        <xs:enumeration value="home"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="sixDigits">
    <xs:restriction base="xs:string">
        <xs:pattern value="\d{6}"/>
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="phoneStructureType">
    <xs:simpleContent>
        <xs:extension base="phoneStructure">
            <xs:attribute name="type" type="forPhone" use="optional"/>
        </xs:extension>
    </xs:simpleContent>
</xs:complexType>

<xs:simpleType name="phoneStructure">
    <xs:restriction base="xs:string">
        <xs:pattern value="\d{3}-\d{2}-\d{2}"/>
    </xs:restriction>
</xs:simpleType>

<xs:element name="notebook">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="offices">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="office" type="OfficeType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="person">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="NameType"/>
                <xs:element name="adress" type="AdressType"/>
                <xs:element name="phones" type="phoneType"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:IDREF" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== pycckuu225/kt2XML/xmlFile.XML
<?xml version="1.0" encoding="UTF-8"?>
<notebook xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="schemaFile.xsd">
      
  <offices>
    <office code="A1">My office</office>
    <office code="A2">My office</office>
  </offices>
  <person id="Ahfjsl" office="A2">
    <name>
        <first>vasia</first>
        <surname>god</surname>
    </name>
    <address>
        <street>123 Main St</street>
        <city>Anytown</city>
        <index>123456</index>
    </address>
    <phones>
        <phone type="work">123-45-67</phone>
        <phone>987-65-43</phone>
    </phones>
  </person>
  <person id="Aasjfks" office="A2">
    <name>
        <first>vasia</first>
        <surname>god</surname>
    </name>
    <address>
        <street>123 Main St</street>
        <city>Anytown</city>
        <index>123456</index>
    </address>
    <phones>
        <phone type="work">123-45-67</phone>
        <phone>987-65-43</phone>
    </phones>
  </person>
</notebook>
